### ISSUE TITLE
Doesn't work with osTicket v1.10.1 (9ae093d)

### ISSUE THREAD

**Issue by jeffnewbold** [clonemeagain/osticket-plugin-responder#1]
Doesn't fire off any error, doesn't really do anything at all.

**Comment by clonemeagain** [comment]
I'll check it out mate, thanks for the report.

First thing you can check is if the plugin itself is enabled.
Then check the config of the plugin, if not configured it won't do anything. Maybe post a screenshot of the config?

**Comment by jeffnewbold** [comment]
Howdy howdy! The config IE which canned response, the UID (I'm using #1)
and the times? Or the actual config.php (if I was supposed to mod that I
did not). It DOES let me enable, and it DOES let me configure, it just
doesn't do anything further. The auto respondering reply does fire off
though so I know osticket is working.
Great work btw - I wouldn't mind donating a few quid your way for
doing this.
Jeff


On Wed, Nov 1, 2017, at 07:13 AM, Aaron wrote:
> I'll check it out mate, thanks for the report.


> First thing you can check is if the plugin itself is enabled.
>  Then check the config of the plugin, if not configured it won't do
>  anything. Maybe post a screenshot of the config?> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/clonemeagain/osticket-plugin-responder/issues/1#issuecomment-341089912

**Comment by clonemeagain** [comment]
Just finished testing it, and the default config should be fine on 1.10.1 if you've selected a Canned Response.

Note: The autoreply only get's sent for tickets when they are created _outside_ of the office-hours entered in the plugin config compared to the database/server's timezone, not whatever time it is for the end-user, so make sure the system timezone is the one you're comparing to.

Example: a new ticket get's created at midnight, you've entered office hours of 0900-1700 M-F, that ticket get's an autoreply. A ticket created at 1200 on Tuesday will not trigger the plugin.

If you want to see more info in the logs, you can modify the class.ResponderPlugin.php file:
```php
  /**
   * Set to TRUE to enable extra logging.
   *
   * @var boolean
   */
  const DEBUG = FALSE;
```
Change `FALSE` to `TRUE` to see the time checks in the logs.  Then every new ticket will show the time calculation in the logs. 

If you want to send an autoresponse for every ticket regardless of the time, you don't need this plugin, just use the default Autoresponder: `Admin -> Settings -> Tickets -> Autoresponder`
You can configure it's template in "New Ticket Autoresponse Template"  under `Admin -> Emails -> Templates -> osTicket Default Template`
This plugin is separate from that, so you can use both if you want!

**Comment by clonemeagain** [comment]
Ok, didn't answer your question: the config of the plugin is the one I mean, like this: 

![responder](https://user-images.githubusercontent.com/5077391/32302876-2ed1195c-bfb9-11e7-8fae-c14bcaf1e180.PNG)

**Comment by jeffnewbold** [comment]
here are the two images:

 

 

 

On Wed, Nov 1, 2017, at 06:33 PM, Aaron wrote:
> Ok, didn't answer your question: the config of the plugin is the one I
> mean, like this:> responder


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/clonemeagain/osticket-plugin-responder/issues/1#issuecomment-341274329

**Comment by jeffnewbold** [comment]
I just moved them all to 0000-0000 to see if it's the time.


On Wed, Nov 1, 2017, at 06:33 PM, Aaron wrote:
> Ok, didn't answer your question: the config of the plugin is the one I
> mean, like this:> responder


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/clonemeagain/osticket-plugin-responder/issues/1#issuecomment-341274329

**Comment by jeffnewbold** [comment]
Just turned debug on - and yes, we already do the auto responder one for
us (which works). Will see what the logging says.
Thanks again for making this, is there a paypal that you have?


On Wed, Nov 1, 2017, at 06:29 PM, Aaron wrote:
> Just finished testing it, and the default config should be fine on
> 1.10.1 if you've selected a Canned Response.> Note: The autoreply only get's sent for tickets when they are created
>       *outside* of the office-hours entered in the plugin config
>       compared to the database/server's timezone, not whatever time it
>       is for the end-user, so make sure the system timezone is the one
>       you're comparing to.> Example: a new ticket get's created at midnight, you've entered office
> hours of 0900-1700 M-F, that ticket get's an autoreply. A ticket
> created at 1200 on Tuesday will not trigger the plugin.> If you want to see more info in the logs, you can modify the
> class.ResponderPlugin.php file:>   /**
>    * Set to TRUE to enable extra logging. *
>    * @var boolean */ const DEBUG = FALSE;> Change FALSE to TRUE to see the time checks in the logs.  Then every
> new ticket will show the time calculation in the logs.> If you want to send an autoresponse for every ticket regardless of the
> time, you don't need this plugin, just use the default Autoresponder:
> Admin -> Settings -> Tickets -> Autoresponder>  You can configure it's template in "New Ticket Autoresponse Template"
>  under Admin -> Emails -> Templates -> osTicket Default Template>  This plugin is separate from that, so you can use both if you want!> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/clonemeagain/osticket-plugin-responder/issues/1#issuecomment-341273576

**Comment by clonemeagain** [comment]
I'm assuming this is working. If not, please use the web interface to post the screenshots.

**Comment by jeffnewbold** [comment]
Oddly enough, it DID start working and I did ... NOTHING. It was very
odd. I just realized it when I tried it this evening so there's that.
You can close it. Thank you again!

On Sat, Nov 11, 2017, at 07:08 PM, Aaron wrote:
> I'm assuming this is working. If not, please use the web interface to
> post the screenshots.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/clonemeagain/osticket-plugin-responder/issues/1#issuecomment-343706218
