### ISSUE TITLE
plugin is not selecting the plugin

### ISSUE THREAD

**Issue by mevinshajan** [clonemeagain/osticket-plugin-responder#3]
Hi

I have added the canned response and save 
but plugin not sending any mail to the users

**Comment by clonemeagain** [comment]
Might need more details mate, such as which version of osticket you're using, a screenshot of the plugin config would be good too

**Comment by mevinshajan** [comment]
i am using the version 1.12 and i configured the plugin also but its not fetching the canned response 
even same issue for auto close plugin also it is closing the ticket and all but not sending the reply to the auto closed ticket both plugin is configured fine but the  Auto-Reply Canned Response:is not changing from the Send no Reply to canned response title (title is showing in the drop down list)

**Comment by MBRCTV** [comment]
having same issue, it says posted but no email is being sent 

![image](https://user-images.githubusercontent.com/39084010/59098494-74855580-88ee-11e9-8c40-9d00a1b400c2.png)

**Comment by mevinshajan** [comment]
I tried with the above link still the problem persist
